### PR TITLE
Identity attribute relationships

### PR DESCRIPTION
**Pull request by ManueGE**
If your JSON has the relationships by referencing the identity attribute instead of by nesting JSONs, you can take advantage of the `identityAttributeRelated` attribute. For example, if your JSON `NSDictionary` is:

```objc
NSDictionary *batman = @{
      @"id": @"1",
      @"name": @"Batman",
      @"publisher": @"1"
      }
````

you may not want Groot to serialize this dictionary by setting 1 to the `Publisher` relationship, but by assigning it with the `Publisher` object which has 1 as its `identityAttribute` value. You accomplish that by associating the identityAttribute key with `true` (or any other positive boolean value) in the entity user info dictionary:

Entity User Info

This way, Groot will search in the publisher entity for a entry with the given identity attribute. If it is found, it will assign this entry as the `Publisher` object of the `Character`; if it doesn't Groot will create a placeholder `Publisher` entry with this value for the identity attribute. This placeholder object would be filled eventually if the new data is provided.

**Note:** To make this feature works, you must always to use the merge methods instead of the insert ones.

### CODE REVIEW

**Comment by ManueGE** [comment]
Includes test cases in the `GRTIdentityRelatedSerializationTests` class.

**Comment by gonzalezreal** [comment]
This is a very interesting feature. Groot is currently being [reimplemented using Swift](https://github.com/gonzalezreal/Groot/tree/swift). Let me know if you'd be interested in providing this feature in that branch as well.

**Comment by ManueGE** [comment]
Sure, I'll implement it when I have some time.

**Comment by ManueGE** [comment]
I've [done it](https://github.com/gonzalezreal/Groot/pull/16). 

Any comments are welcome.

**Comment by gonzalezreal** [comment]
Thanks! I will look into it as soon as I have some spare time.

**Comment by gonzalezreal** [comment]
There has been a lot of internal changes for milestone 1.0, so this PR is kind of updated. In any case your contribution was very useful and effectively has been the seed for #26. Thanks a lot!

**Pull request closed without merging**
